name: care_sync
description: "CareSync - Medical Booking Application"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking & API
  dio: ^5.9.2
  http: ^1.6.0
  supabase_flutter: ^2.15.0

  # State Management & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^17.3.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Styling
  flutter_screenutil: ^5.9.3
  skeletonizer: ^2.1.3
  cached_network_image: ^3.4.1
  lottie: ^3.3.3

  # Hardware & Services
  image_picker: ^1.2.2
  flutter_stripe: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800

