name: care_sync
description: "CareSync - Medical Booking Application"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking & API
  dio: ^5.9.2
  http: ^1.6.0
  supabase_flutter: ^2.15.0

  # State Management & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^17.3.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Styling
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  skeletonizer: ^2.1.3
  cached_network_image: ^3.4.1
  lottie: ^3.3.3

  # Hardware & Services
  image_picker: ^1.2.2
  flutter_stripe: ^13.0.0
  flutter_svg: ^2.3.0
  pinput: ^6.0.2
  flutter_spinkit: ^5.2.2
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        # Regular (w400)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        # ExtraLight (w200)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        # Light (w300)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        # Medium (w500)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        # SemiBold (w600)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Bold (w700)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        # ExtraBold (w800)
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

